# Generated by Django 2.2.2 on 2019-06-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190614_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Delhi', 'Delhi'), ('Tricity', 'Tricity')], max_length=100)),
                ('city', models.CharField(choices=[('Delhi', 'Delhi'), ('Tricity', 'Tricity')], max_length=100)),
                ('mind_o', models.IntegerField()),
                ('body_o', models.IntegerField()),
                ('skin_o', models.IntegerField()),
                ('multipack_o', models.IntegerField()),
                ('mind_c', models.IntegerField()),
                ('body_c', models.IntegerField()),
                ('skin_c', models.IntegerField()),
                ('multipack_c', models.IntegerField()),
                ('jumbo_combos', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
