# Generated by Django 2.2.2 on 2019-07-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190716_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='city',
        ),
        migrations.RemoveField(
            model_name='group',
            name='city',
        ),
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='trade',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
