# Generated by Django 2.2.2 on 2019-07-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190716_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trade'),
        ),
    ]
