# Generated by Django 2.2.2 on 2019-08-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190716_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='num_samplings',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('mind', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('skin', models.CharField(max_length=100)),
                ('multipack', models.CharField(max_length=100)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FormSubmission')),
            ],
        ),
    ]
